### ISSUE TITLE
How is the wine wrapper app constructed?

### ISSUE THREAD

**Issue by secondfolder** [Ferbez/virtual-succubus-macos#3]
Very cool project! Thanks for making it :)

There are some other games I'd love to make a wine wrapper app for like you have with Virtual Succubus so I've been trying to understanding how you've built this wrapper. You've obviously committed part of the wrapper app itself but I can't see any see any scripts for creating that app in the first place. Are you building it with some bash scripts? Or do you have an xcode project for that? If so is that something you'd consider releasing (or at least sharing with me directly) so I can learn more about how the process works in order to make my own?

Also I downloaded the released app and based on the [d3dmetal script](https://github.com/Ferbez/virtual-succubus-macos) I was expecting to find both a `wine` directory and a `prefix` directory in the `Resources` directory of the app but I could only see a `wine` directory. So I'm confused as to how that works. What is it I'm missing?
<img width="523" alt="image" src="https://github.com/user-attachments/assets/2753a483-488e-4e24-afce-890aeb3a5718">

Thanks for you consideration,
Callum

**Comment by Ferbez** [comment]
Hi! This wrapper is really simple - it's just shell script which is present in this repository and should be pretty self-explanatory (you should try opening executable with your favorite text editor). I was using slightly modified Wine build earlier, but now there's no need for that - it's just WS11WineCX64Bit23.7.1. About directories - `prefix` folder is created on first startup, there's no need for it to be present before that.

There's obviously nothing preventing you from using this wrapper as a base for other games - I do that myself a lot since I like my Wine apps to look as native as possible.

**Comment by secondfolder** [comment]
Amazing! Thanks for so much detail :)

> prefix folder is created on first startup

Ah! I see what's happening. I was assuming [this line](https://github.com/Ferbez/virtual-succubus-macos/blob/9e53fd49257312e9030883fda974afec29fea4d2/Virtual%20Succubus.app/Contents/MacOS/d3dmetal#L9) was responsible for the creation the prefix directory but when I ran the app I wasn't seeing any prefix directory even though I was getting the installation archive file prompt (indicating that earlier line had run). I've just worked out what was happening though. I was running the app when it was still inside the dmg volume since I was just testing it, and since the volume is read-only I believe that line was failing but since zsh's default behavior is not to exit the script when a line fails it was still showing the file prompt.

There's just one last thing I'm unsure of. Where does the contents of the Frameworks directory come from? Everything else I think I understand now:

```
Virtual Succubus.app
├─ Contents/
│  ├─ Frameworks/
│  │  ├─ ...            <-- Not sure where these contents comes from
│  ├─ MacOS/
│  │  ├─ d3dmetal       <-- From https://github.com/Ferbez/virtual-succubus-macos/blob/main/Virtual%20Succubus.app/Contents/MacOS/d3dmetal
│  ├─ Resources/
│  │  ├─ wine/
│  │  │  ├─ ...         <-- WS11WineCX64Bit23.7.1 taken from https://github.com/The-Wineskin-Project/Engines/releases or maybe built from source
│  │  ├─ icon.icns      <-- I assume you've made this based off the icn from the windows app
│  │  ├─ windowed.reg   <-- I assume you manually created this based off what registry entries the windows app created when changing to full screen
```

Also very cool about shc. First time I've herd of that project but seems like a good tool to know about for the right occasion.

Thanks again for taking the time to help me grok things!

**Comment by Ferbez** [comment]
> but since zsh's default behavior is not to exit the script when a line fails

Though catching errors would be a good thing - I'll likely look into it for the next update.

>Where does the contents of the Frameworks directory come from?

Those are libraries necessary for Wine to run - you can either build them from source or (maybe) get them prebuilt somewhere.

**Comment by secondfolder** [comment]
Great, thanks again for taking the time to reply. I’ll go ahead and close the ticket now :)
